USE T_Opflix;

CREATE TABLE Usuarios(
	IdUsuario INT PRIMARY KEY IDENTITY
	,Email VARCHAR(200) NOT NULL
	,Senha VARCHAR(200) NOT NULL
	,Permissao VARCHAR(7) NOT NULL
);
CREATE TABLE FS(
	IdFS INT PRIMARY KEY IDENTITY
	,Qual VARCHAR(50)
);
CREATE TABLE Plataforma (
	IdPlataforma INT PRIMARY KEY IDENTITY NOT NULL
	,Nome VARCHAR(200) NOT NULL
);
CREATE TABLE Categorias (
	IdCategoria INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(100) NOT NULL
);
CREATE TABLE Conteudo(
		IdConteudo INT PRIMARY KEY IDENTITY
		,Titulo VARCHAR(255) NOT NULL
		,Sinopse VARCHAR(255) NOT NULL
		,DLanc DATE NOT NULL
		,Duracao TIME NOT NULL
		,IdCategoria INT FOREIGN KEY REFERENCES Categorias (IdCategoria)
		,IdFS  INT FOREIGN KEY REFERENCES FS (IdFS)
		,IdPlataforma INT FOREIGN KEY REFERENCES Plataforma (IdPlataforma)
);


CREATE TABLE Favoritos(
	IdFavorito INT PRIMARY KEY IDENTITY 
	,IdConteudo INT FOREIGN KEY REFERENCES Conteudo (IdConteudo)
	,IdUsuario INT FOREIGN KEY REFERENCES Usuarios (IdUsuario)
);

ALTER TABLE dbo.Usuarios ADD IdPermissao INT FOREIGN KEY REFERENCES Permissao (IdPermissao);
SELECT * FROM Usuarios
ALTER TABLE dbo.Usuarios DROP COLUMN CPF;
DROP TABLE Usuarios;
DROP TABLE Favoritos;


ALTER TABLE Usuarios ADD CPF BIGINT NOT NULL ;

SELECT * FROM Usuarios